"""Render analysis results as a readable Markdown report."""

from __future__ import annotations

from .analyzer import AxisResult
from .checklist import CHECKLIST

_BY_ID = {item.id: item for item in CHECKLIST}


def to_markdown(results: list[AxisResult], story_name: str = "story") -> str:
    flagged = [r for r in results if r.ai_leaning_present]
    clean = [r for r in results if not r.ai_leaning_present]

    lines = [
        f"# Narrative-humanizer report: {story_name}",
        "",
        f"{len(flagged)} of {len(results)} checklist axes show the AI-leaning default.",
        "",
    ]

    if flagged:
        lines.append("## Flagged axes")
        lines.append("")
        for r in flagged:
            item = _BY_ID.get(r.id)
            if item is None:
                continue
            lines += [
                f"### {item.name}",
                f"- **AI-leaning default:** {item.ai_default}",
                f"- **Evidence:** {r.evidence}",
                f"- **Human-leaning alternative:** {item.human_leaning}",
                f"- **Suggested edit:** {r.suggested_edit or item.fix}",
                f"- _Reference stat: {item.stat}_",
                "",
            ]

    if clean:
        lines.append("## Axes already human-leaning")
        lines.append("")
        for r in clean:
            item = _BY_ID.get(r.id)
            name = item.name if item else r.id
            lines.append(f"- {name}")
        lines.append("")

    lines.append(
        "---\n_Generated by narrative-humanizer, an independent tool inspired by "
        "StoryScope (COLM 2026, arXiv:2604.03136). These are structural tendencies "
        "from one benchmark, not a guarantee against any detector._"
    )
    return "\n".join(lines)
